name: Build mupen64plus

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

		- name: get modules
      run: |
				git submodule init
				git submodule update libmupen64plus/mupen64plus-win32-deps
        
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
        toolset: 16.0
    
    - name: Build
      run: msbuild libmupen64plus/mupen64plus-sln/projects/msvc11/mupen64plus.sln
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: dlls
        path: Assets/dll/mupen64plus.dll
